name:         bittrex
version:      "0.1.0.0"
author:       Maciej Kazulak
maintainer:   kazulakm@gmail.com
stability:    experimental
license:      MIT 
license-file: LICENSE
category:     Network
build-type:   Simple

default-extensions:
  - OverloadedStrings

extra-source-files:
  - README.md

library:
  dependencies:
    - aeson
    - aeson-pretty
    - base
    - ixset
    - random
    - unordered-containers
    - websockets
    - wuss
    - url
    - bytestring
